### DISCUSSION TITLE
Deploy Stable Studio to AWS VM with GitHub Actions

### DISCUSSION THREAD

**Discussion by mickmcgrath13** [Stability-AI/StableStudio#61] [Show and tell]
With a simple `Dockerfile` and a `docker-compose.yaml` file ([like in this PR](https://github.com/Stability-AI/StableStudio/pull/58)), I'm currently able to deploy https://github.com/Stability-AI/StableStudio/pull/58 using [this deploy docker to ec2 action](https://github.com/bitovi/github-actions-deploy-docker-to-ec2) by creating the following file:
`.github/workflows/deploy-main.yml`
```
name: deploy-ec2
on:
  push:
    branches: [ main ]

jobs:
  deploy-ec2:
    environment:
      name: ${{ github.ref_name }}
      url: ${{ steps.deploy.outputs.vm_url }}
    runs-on: ubuntu-latest
    steps:
      - id: deploy
        uses: bitovi/github-actions-deploy-docker-to-ec2@ansible-include-dot-files
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_default_region: us-east-1
          aws_ami_id: ami-0f1bae6c3bedcc3b5
          ec2_volume_size: 100
          app_port: 3000
          lb_healthcheck: TCP:3000
          ec2_instance_type: m6i.large           # 2vCPU, 8GB RAM
          dot_env: ${{ secrets.DOT_ENV }}
```

The action has a nice getting started video.
